window.PANORAMA_SUPABASE={url:"https://dtmhffgpwxzdncbuoohb.supabase.co",key:"sb_publishable_S_wZkfLNvx0mnHBLGHcfgg_Q_SkycdW"};

/* Exportador XLSX real y offline para Panorama Finanzas. */
(function(){
  const STORAGE='panorama_finanzas_pf_v1_010';
  const enc=new TextEncoder();
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
  const flat=v=>v==null?'':Array.isArray(v)?v.map(flat).join(', '):typeof v==='object'?Object.entries(v).map(([k,x])=>k+': '+flat(x)).join(' | '):v;
  const rows=v=>(Array.isArray(v)?v:[]).map(x=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).map(([k,v])=>[k,flat(v)])):{Valor:flat(x)});
  const crcTable=(()=>{const t=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0;}return t;})();
  const crc32=b=>{let c=0xffffffff;for(const x of b)c=crcTable[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0;};
  const u16=n=>[n&255,(n>>>8)&255],u32=n=>[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255];
  function zip(files){let parts=[],central=[],offset=0;for(const f of files){const name=enc.encode(f.name),data=enc.encode(f.data),crc=crc32(data),local=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...name,...data]);parts.push(local);central.push(new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),...name]));offset+=local.length;}const csize=central.reduce((s,x)=>s+x.length,0),eocd=new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(files.length),...u16(files.length),...u32(csize),...u32(offset),...u16(0)]);return new Blob([...parts,...central,eocd],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});}
  const col=n=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;};
  function worksheet(data){const rs=rows(data),keys=[...new Set(rs.flatMap(r=>Object.keys(r)))];const all=keys.length?[keys,...rs.map(r=>keys.map(k=>r[k]))]:[['Sin registros']];return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+all.map((r,i)=>'<row r="'+(i+1)+'">'+r.map((v,j)=>{const ref=col(j)+(i+1);if(i>0&&typeof v==='number'&&Number.isFinite(v))return '<c r="'+ref+'"><v>'+v+'</v></c>';return '<c r="'+ref+'" t="inlineStr"><is><t xml:space="preserve">'+esc(v)+'</t></is></c>';}).join('')+'</row>').join('')+'</sheetData></worksheet>';}
  function exportXlsx(){let s={};try{s=JSON.parse(localStorage.getItem(STORAGE)||'{}')||{};}catch(e){alert('No se pudieron leer los datos para exportarlos.');return;}const now=new Date(),stamp=now.toISOString().slice(0,10),sheets=[['Resumen',[{Generado:now.toLocaleString('es-MX'),Movimientos:(s.moves||[]).length,Cuentas:(s.accounts||[]).length,Proveedores:(s.providers||[]).length,Compromisos:(s.commitments||[]).length,Empleados:(s.payrollEmployees||[]).length}]],['Cuentas',s.accounts],['Movimientos',s.moves],['Proveedores',s.providers],['Pagos proveedores',s.providerPayments],['Compromisos',s.commitments],['Pagos compromisos',s.commitmentPayments],['Empleados nómina',s.payrollEmployees],['Periodos nómina',s.payrollPeriods],['Pagos fijos',s.fixedPayments],['Cortes',s.cuts],['Conciliaciones',s.reconciliations],['Cierres POS',s.posCloses],['Ajustes',s.adjustments],['Loyverse resumen',s.loyverseSummaries],['Loyverse tesorería',s.loyverseTreasuryExpenses],['Categorías entrada',s.categories?.entrada],['Categorías salida',s.categories?.salida],['Categorías compromisos',s.categories?.compromiso]];
    const files=[
      {name:'[Content_Types].xml',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'+sheets.map((_,i)=>'<Override PartName="/xl/worksheets/sheet'+(i+1)+'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>').join('')+'</Types>'},
      {name:'_rels/.rels',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'},
      {name:'xl/workbook.xml',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+sheets.map((x,i)=>'<sheet name="'+esc(x[0]).slice(0,31)+'" sheetId="'+(i+1)+'" r:id="rId'+(i+1)+'"/>').join('')+'</sheets></workbook>'},
      {name:'xl/_rels/workbook.xml.rels',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+sheets.map((_,i)=>'<Relationship Id="rId'+(i+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'+(i+1)+'.xml"/>').join('')+'<Relationship Id="rId'+(sheets.length+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'},
      {name:'xl/styles.xml',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="1"><font><sz val="11"/><name val="Calibri"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="1"><xf xfId="0"/></cellXfs></styleSheet>'},
      ...sheets.map((x,i)=>({name:'xl/worksheets/sheet'+(i+1)+'.xml',data:worksheet(x[1])}))
    ];const blob=zip(files),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Panorama_Finanzas_'+stamp+'.xlsx';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},1000);}
  document.addEventListener('click',function(e){const b=e.target.closest&&e.target.closest('#btnExportData,#btnExportExcel');if(!b)return;e.preventDefault();e.stopImmediatePropagation();exportXlsx();},true);
  window.PanoramaFinanceXlsx={export:exportXlsx};
})();