/* Panorama Finanzas — exportación XLSX real */
(function(){
const KEY='panorama_finanzas_pf_v1_010',enc=new TextEncoder();
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const flat=v=>v==null?'':Array.isArray(v)?v.map(flat).join(', '):typeof v==='object'?Object.entries(v).map(([k,x])=>k+': '+flat(x)).join(' | '):v;
const rows=v=>(Array.isArray(v)?v:[]).map(x=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).map(([k,y])=>[k,flat(y)])):{valor:flat(x)});
function sheet(name,data){const r=rows(data),cols=[...new Set(r.flatMap(x=>Object.keys(x)))],all=cols.length?[cols,...r.map(x=>cols.map(k=>x[k]))]:[['Sin registros']];let xml='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>';all.forEach((row,i)=>{xml+='<row r="'+(i+1)+'">';row.forEach((v,j)=>{const n=Number(v),num=typeof v==='number'&&Number.isFinite(n),cell=String.fromCharCode(65+j)+(i+1);xml+='<c r="'+cell+'"'+(num?'':' t="inlineStr"')+'>'+(num?'<v>'+n+'</v>':'<is><t>'+esc(v)+'</t></is>')+'</c>';});xml+='</row>';});return xml+'</sheetData></worksheet>';}
function crc(a){let c=~0;for(const b of a){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xEDB88320:0)}return (~c)>>>0}
const u16=n=>[n&255,n>>>8&255],u32=n=>[n&255,n>>>8&255,n>>>16&255,n>>>24&255];
function zip(files){let out=[],central=[],off=0;for(const [name,text] of files){const d=enc.encode(text),nb=enc.encode(name),z=crc(d),head=[80,75,3,4,20,0,0,0,0,0,0,0,0,0,...u32(z),...u32(d.length),...u32(d.length),...u16(nb.length),0,...nb];out.push(...head,...d);const cd=[80,75,1,2,20,0,20,0,0,0,0,0,0,0,...u32(z),...u32(d.length),...u32(d.length),...u16(nb.length),0,0,0,0,0,0,0,0,...u32(off),...nb];central.push(...cd);off+=head.length+d.length}const start=off,csize=central.length;out.push(...central,80,75,5,6,0,0,0,0,...u16(files.length),...u16(files.length),...u32(csize),...u32(start),0,0);return new Blob([new Uint8Array(out)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
function exportXlsx(){let s={};try{s=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){alert('No se pudieron leer los datos.');return}const now=new Date(),date=now.toISOString().slice(0,10),tabs=[['Resumen',[{generado:now.toLocaleString('es-MX'),movimientos:(s.moves||[]).length,cuentas:(s.accounts||[]).length,proveedores:(s.providers||[]).length,empleados:(s.payrollEmployees||[]).length}]],['Cuentas',s.accounts],['Movimientos',s.moves],['Proveedores',s.providers],['Pagos proveedores',s.providerPayments],['Compromisos',s.commitments],['Pagos compromisos',s.commitmentPayments],['Empleados nómina',s.payrollEmployees],['Periodos nómina',s.payrollPeriods],['Pagos fijos',s.fixedPayments],['Cortes',s.cuts],['Conciliaciones',s.reconciliations],['Cierres POS',s.posCloses],['Ajustes',s.adjustments],['Loyverse resumen',s.loyverseSummaries],['Loyverse tesorería',s.loyverseTreasuryExpenses],['Categorías entrada',s.categories?.entrada],['Categorías salida',s.categories?.salida],['Categorías compromisos',s.categories?.compromiso]];const safe=tabs.map((x,i)=>[String(x[0]).slice(0,31),x[1],i+1]),files=[['[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'+safe.map(x=>'<Override PartName="/xl/worksheets/sheet'+x[2]+'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>').join('')+'</Types>'],['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+safe.map(x=>'<sheet name="'+esc(x[0])+'" sheetId="'+x[2]+'" r:id="rId'+x[2]+'"/>').join('')+'</sheets></workbook>'],['xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+safe.map(x=>'<Relationship Id="rId'+x[2]+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'+x[2]+'.xml"/>').join('')+'</Relationships>']];safe.forEach(x=>files.push(['xl/worksheets/sheet'+x[2]+'.xml',sheet(x[0],x[1])]));const a=document.createElement('a');a.href=URL.createObjectURL(zip(files));a.download='Panorama_Finanzas_'+date+'.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.addEventListener('click',e=>{const b=e.target.closest('#btnExportData');if(b){e.preventDefault();e.stopImmediatePropagation();exportXlsx()}},true);window.PanoramaExportXlsx=exportXlsx;
})();