create table if not exists private.finance_commitments(id text primary key,name text not null,total numeric(14,2) not null check(total>0),paid_amount numeric(14,2) not null default 0 check(paid_amount>=0 and paid_amount<=total),active boolean not null default true);
create table if not exists private.finance_commitment_payments(id text primary key,commitment_id text not null references private.finance_commitments(id),occurred_on date not null,amount numeric(14,2) not null check(amount>0),account_id text not null references private.finance_accounts(id),ledger_entry_id text references private.finance_ledger_entries(id),status text not null default 'posted' check(status in('posted','reversed')));
alter table private.finance_commitments add column if not exists category text not null default 'otro_compromiso';
alter table private.finance_commitments add column if not exists due_date date;
alter table private.finance_commitments add column if not exists note text not null default '';
alter table private.finance_commitments add column if not exists created_at timestamptz not null default now();
alter table private.finance_commitments add column if not exists updated_at timestamptz not null default now();
alter table private.finance_commitment_payments add column if not exists note text not null default '';
alter table private.finance_commitment_payments add column if not exists created_at timestamptz not null default now();
alter table private.finance_commitment_payments add column if not exists updated_at timestamptz not null default now();
create index if not exists finance_commitments_active_idx on private.finance_commitments(active,due_date);
create index if not exists finance_commitment_payments_commitment_idx on private.finance_commitment_payments(commitment_id,occurred_on);
create index if not exists finance_commitment_payments_account_idx on private.finance_commitment_payments(account_id,occurred_on);
alter table private.finance_commitments enable row level security;
alter table private.finance_commitment_payments enable row level security;
drop policy if exists finance_commitments_access on private.finance_commitments;
create policy finance_commitments_access on private.finance_commitments for all to authenticated using((select private.has_panorama_finanzas_access())) with check((select private.has_panorama_finanzas_access()));
drop policy if exists finance_commitment_payments_access on private.finance_commitment_payments;
create policy finance_commitment_payments_access on private.finance_commitment_payments for all to authenticated using((select private.has_panorama_finanzas_access())) with check((select private.has_panorama_finanzas_access()));