-- Panorama Finanzas: secure all public RPC wrappers that delegate to private ledger functions
alter function public.adjust_finance_account_balance(text,date,text,numeric,text,jsonb) security definer;
alter function public.adjust_finance_account_balance(text,date,text,numeric,text,jsonb) set search_path = public, private, pg_temp;
alter function public.archive_finance_commitment(text) security definer;
alter function public.archive_finance_commitment(text) set search_path = public, private, pg_temp;
alter function public.pay_finance_fixed_payment(text) security definer;
alter function public.pay_finance_fixed_payment(text) set search_path = public, private, pg_temp;
alter function public.post_commitment_payment(text,date,text,numeric,text,text) security definer;
alter function public.post_commitment_payment(text,date,text,numeric,text,text) set search_path = public, private, pg_temp;
alter function public.post_loyverse_treasury_expense(text,text,date,numeric,text,text,text,text) security definer;
alter function public.post_loyverse_treasury_expense(text,text,date,numeric,text,text,text,text) set search_path = public, private, pg_temp;
alter function public.post_provider_payment(text,date,text,numeric,text,text) security definer;
alter function public.post_provider_payment(text,date,text,numeric,text,text) set search_path = public, private, pg_temp;
alter function public.post_provider_purchase(text,date,text,numeric,text,text,text) security definer;
alter function public.post_provider_purchase(text,date,text,numeric,text,text,text) set search_path = public, private, pg_temp;
alter function public.reverse_commitment_payment(text,text,text) security definer;
alter function public.reverse_commitment_payment(text,text,text) set search_path = public, private, pg_temp;
alter function public.reverse_finance_entry(text,text,date,text) security definer;
alter function public.reverse_finance_entry(text,text,date,text) set search_path = public, private, pg_temp;
alter function public.reverse_finance_fixed_payment(text,text,text) security definer;
alter function public.reverse_finance_fixed_payment(text,text,text) set search_path = public, private, pg_temp;
alter function public.reverse_loyverse_treasury_expense(text,text,text) security definer;
alter function public.reverse_loyverse_treasury_expense(text,text,text) set search_path = public, private, pg_temp;
alter function public.reverse_provider_payment(text,text,text) security definer;
alter function public.reverse_provider_payment(text,text,text) set search_path = public, private, pg_temp;
alter function public.reverse_provider_purchase(text,text,text) security definer;
alter function public.reverse_provider_purchase(text,text,text) set search_path = public, private, pg_temp;
alter function public.upsert_finance_commitment(text,text,text,numeric,date,text) security definer;
alter function public.upsert_finance_commitment(text,text,text,numeric,date,text) set search_path = public, private, pg_temp;
alter function public.upsert_finance_fixed_payment(text,text,numeric,date,text,text,text) security definer;
alter function public.upsert_finance_fixed_payment(text,text,numeric,date,text,text,text) set search_path = public, private, pg_temp;
alter function public.upsert_finance_provider(text,text,text,text) security definer;
alter function public.upsert_finance_provider(text,text,text,text) set search_path = public, private, pg_temp;